### ISSUE TITLE
odd clocks in device tree 

### ISSUE THREAD

**Issue by frantony** [RC-MODULE/linux-3.10.x#1]
The MB7707 board has 6 clock chips:
- 25.000 MHz
- 12.000 MHz
- 12.288 MHz
- 74.250 MHz
- 27.000 MHz
- 48.000 MHz

But in module-mb7707.dts we have these fixed-clocks:
- 324 MHz
- 162 MHz
- 81 MHz
- 54 MHz
- 27 MHz

Also there are some clock magic constants in module-mb7707.dts:
- 325 MHz (cpu clock) (sic! do you mean 324 indeed?)
- 54 MHz (i2c, uart)
- 81 MHz (i2c0)

A resonable solution is:
- add necessary code for describing your clock dividers;
- move all derivative clocks to module-k1879x.dtsi;
- put definitions for real reference clocks into module-mb7707.dts.

See also my commit comment:

https://github.com/RC-MODULE/linux-3.10.x/commit/50ccc0905d742fc4e3248199aec2aa7b53181786#commitcomment-6363068

**Comment by nekromant** [comment]
Thanks for reporting, we'll investigate this and fix ASAP.

**Comment by nekromant** [comment]
@frantony Should be finally fixed in K1879-3.19.2 branch
