### ISSUE TITLE
gcc 4.9.2 compile error

### ISSUE THREAD

**Issue by Abelard0** [RC-MODULE/linux-3.10.x#5]
gcc 4.9.2 deny to compile kernel because of errors 
1) "arch/arm/mach-uemd/uemd.c:249:2: ошибка: «r» undeclared (first use in this function)
  r = ioread32((void __iomem*)0xf8033084);"
2)drivers/gpio/gpio-module.c:43:2: error: implicit declaration of function 'uemd_is_virgin' [-Werror=implicit-function-declaration]
  if (!uemd_is_virgin())

Also as I understand there is no need in "uemd_timer" variable definition in  arch/arm/mach-uemd/timer.c:99

**Comment by nekromant** [comment]
Спасибо, поправим в понедельник. Ближайшее время так же будет досупна 3.18.х ветка

**Comment by nekromant** [comment]
@Abelard0 
1. Воспроизводится при включенном TSP. Сейчас поправлено. Для Вашего приложения критичен демультиплексор транспортного потока?
2. Поправлено. 
3. Работа с таймерами и весь платформенный код отрефакторены в экспериментальных 4.x ветках
