### ISSUE TITLE
HDMI video out

### ISSUE THREAD

**Issue by marokkoav** [RC-MODULE/linux-3.10.x#6]
С ядром собранным из этих исходников не выводится изображение на монитор через HDMI, видно только сообщение «Input signal out of range». При этом с ядром из прошивки fw-debian-jessie-3.10-ubifs-21012015.tgz HDMI работает нормально. Соответствуют ли эти исходники тем, из которых было собрано ядро для последней прошивки?

**Comment by nekromant** [comment]
Теперь соответствуют, спасибо что сообщили,
