### ISSUE TITLE
Kernel freezes when booting

### ISSUE THREAD

**Issue by dandemidow** [RC-MODULE/linux-3.10.x#7]
Иногда ядро зависает при загрузке.
Останавливается на строчке:
ledtrig-cpu: registered to indicate activity on CPUs

Есть подозрение, что зависает где-то в районе mcrypto.c, в 
static int of_mcrypto_probe(struct platform_device *pdev)
при выполнении
crypto_register_alg(&mcrypto_3des_ecb_alg);

**Comment by nekromant** [comment]
C выключенным драйвером mcrypto таких зависаний не происходит, я правильно понимаю? Можете предоставить конфиг ядра на котором это воспроизводится и каким тулчейном оно собиралось или версию готовой прошивки, если ядро не пересобиралось?

**Comment by dandemidow** [comment]
По крайней мере, с выключенным mcrypto на зависания не попадал. 

Конфиг ядра https://github.com/dandemidow/kernel_cong/blob/master/.config
на основе uemd_defconfig

> arm-linux-gnueabihf-gcc -v
> Используются внутренние спецификации.
> COLLECT_GCC=arm-linux-gnueabihf-gcc
> COLLECT_LTO_WRAPPER=/home/danila/mb7707/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../libexec/gcc/arm-linux-gnueabihf/4.8.3/lto-wrapper
> Целевая архитектура: arm-linux-gnueabihf
> Параметры конфигурации: /cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/src/gcc-linaro-4.8-2014.01/configure --build=i686-build_pc-linux-gnu --host=i686-build_pc-linux-gnu --target=arm-linux-gnueabihf --prefix=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/install --with-sysroot=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/install/arm-linux-gnueabihf/libc --enable-languages=c,c++,fortran --disable-multilib --enable-multiarch --with-arch=armv6 --with-tune=arm1176jz-s --with-fpu=vfp --with-float=hard --with-pkgversion='crosstool-NG linaro-1.13.1-4.8-2014.01 - Linaro GCC 2013.11' --with-bugurl=https://bugs.launchpad.net/gcc-linaro --enable-__cxa_atexit --enable-libmudflap --enable-libgomp --enable-libssp --with-gmp=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --with-mpfr=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --with-mpc=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --with-isl=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --with-cloog=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --with-libelf=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --enable-threads=posix --disable-libstdcxx-pch --enable-linker-build-id --enable-plugin --enable-gold --with-local-prefix=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/install/arm-linux-gnueabihf/libc --enable-c99 --enable-long-long --with-float=hard
> Модель многопоточности: posix
> gcc версия 4.8.3 20140106 (prerelease) (crosstool-NG linaro-1.13.1-4.8-2014.01 - Linaro GCC 2013.11)

**Comment by nekromant** [comment]
Понятно, спасибо. Попробуем воспроизвести на нашей стороне.

**Comment by nekromant** [comment]
Исправлено в бранче 3.10.90.

Свежие прошивки: http://www.module.ru/mb7707/ci/firmware/
